# Generated by Django 5.2.17 on 2026-09-07 23:29

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.extensions
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        django.contrib.postgres.operations.CreateExtension(name="postgis"),
        django.contrib.postgres.operations.CreateExtension(name="pgcrypto"),
        pgvector.django.extensions.VectorExtension(),
        migrations.CreateModel(
            name="Atractivo",
            fields=[
                (
                    "id_atractivo",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("direccion", models.CharField(blank=True, max_length=300, null=True)),
                ("duracion_minutos", models.IntegerField(blank=True, null=True)),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(
                        spatial_index=False, srid=4326
                    ),
                ),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, spatial_index=False, srid=4326
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "atractivo",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id_categoria",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "categoria",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.SmallAutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=80)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "rol",
            },
        ),
        migrations.CreateModel(
            name="TipoTarifa",
            fields=[
                (
                    "id_tipo_tarifa",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                ("codigo", models.CharField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "tipo_tarifa",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id_usuario",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password_hash", models.CharField(max_length=255)),
                ("nombre", models.CharField(max_length=150)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="AtractivoCategoria",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "atractivo",
                    models.ForeignKey(
                        db_column="id_atractivo",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atractivo_categorias",
                        to="turismo.atractivo",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        db_column="id_categoria",
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="atractivo_categorias",
                        to="turismo.categoria",
                    ),
                ),
            ],
            options={
                "db_table": "atractivo_categoria",
            },
        ),
        migrations.AddField(
            model_name="atractivo",
            name="categorias",
            field=models.ManyToManyField(
                related_name="atractivos",
                through="turismo.AtractivoCategoria",
                to="turismo.categoria",
            ),
        ),
        migrations.CreateModel(
            name="FuenteDocumental",
            fields=[
                (
                    "id_fuente",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=250)),
                ("url", models.TextField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_actualizacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "atractivo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_atractivo",
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuentes",
                        to="turismo.atractivo",
                    ),
                ),
            ],
            options={
                "db_table": "fuente_documental",
            },
        ),
        migrations.CreateModel(
            name="FragmentoDocumental",
            fields=[
                (
                    "id_fragmento",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("numero_fragmento", models.IntegerField()),
                ("contenido", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "fuente",
                    models.ForeignKey(
                        db_column="id_fuente",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fragmentos",
                        to="turismo.fuentedocumental",
                    ),
                ),
            ],
            options={
                "db_table": "fragmento_documental",
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                ("id_horario", models.BigAutoField(primary_key=True, serialize=False)),
                ("dia_semana", models.SmallIntegerField()),
                ("hora_apertura", models.TimeField(blank=True, null=True)),
                ("hora_cierre", models.TimeField(blank=True, null=True)),
                ("cerrado", models.BooleanField(default=False)),
                ("vigente_desde", models.DateField(blank=True, null=True)),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "atractivo",
                    models.ForeignKey(
                        db_column="id_atractivo",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="turismo.atractivo",
                    ),
                ),
            ],
            options={
                "db_table": "horario",
            },
        ),
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                ("id_tarifa", models.BigAutoField(primary_key=True, serialize=False)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(default="BOB", max_length=3)),
                ("vigente_desde", models.DateField(blank=True, null=True)),
                ("vigente_hasta", models.DateField(blank=True, null=True)),
                (
                    "observacion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "atractivo",
                    models.ForeignKey(
                        db_column="id_atractivo",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="turismo.atractivo",
                    ),
                ),
                (
                    "tipo_tarifa",
                    models.ForeignKey(
                        db_column="id_tipo_tarifa",
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tarifas",
                        to="turismo.tipotarifa",
                    ),
                ),
            ],
            options={
                "db_table": "tarifa",
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "fecha_asignacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        db_column="id_rol",
                        db_index=False,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="usuario_roles",
                        to="turismo.rol",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_roles",
                        to="turismo.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "usuario_rol",
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="roles",
            field=models.ManyToManyField(
                related_name="usuarios", through="turismo.UsuarioRol", to="turismo.rol"
            ),
        ),
        migrations.AddIndex(
            model_name="atractivocategoria",
            index=models.Index(fields=["categoria"], name="idx_atractivo_categoria"),
        ),
        migrations.AddConstraint(
            model_name="atractivocategoria",
            constraint=models.UniqueConstraint(
                fields=("atractivo", "categoria"), name="pk_atractivo_categoria"
            ),
        ),
        migrations.AddIndex(
            model_name="atractivo",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["ubicacion"], name="idx_atractivo_ubicacion_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="atractivo",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["area"], name="idx_atractivo_area_gist"
            ),
        ),
        migrations.AddConstraint(
            model_name="atractivo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duracion_minutos__isnull", True),
                    ("duracion_minutos__gt", 0),
                    _connector="OR",
                ),
                name="ck_atractivo_duracion",
            ),
        ),
        migrations.AddIndex(
            model_name="fuentedocumental",
            index=models.Index(fields=["atractivo"], name="idx_fuente_atractivo"),
        ),
        migrations.AddIndex(
            model_name="fragmentodocumental",
            index=pgvector.django.indexes.HnswIndex(
                fields=["embedding"],
                name="idx_fragmento_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="fragmentodocumental",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero_fragmento__gte", 0)),
                name="ck_fragmento_numero",
            ),
        ),
        migrations.AddConstraint(
            model_name="fragmentodocumental",
            constraint=models.UniqueConstraint(
                fields=("fuente", "numero_fragmento"), name="uq_fragmento_fuente_numero"
            ),
        ),
        migrations.AddIndex(
            model_name="horario",
            index=models.Index(
                fields=["atractivo", "dia_semana"], name="idx_horario_atractivo_dia"
            ),
        ),
        migrations.AddConstraint(
            model_name="horario",
            constraint=models.CheckConstraint(
                condition=models.Q(("dia_semana__gte", 1), ("dia_semana__lte", 7)),
                name="ck_horario_dia",
            ),
        ),
        migrations.AddConstraint(
            model_name="horario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cerrado", True),
                    models.Q(
                        ("hora_apertura__isnull", False),
                        ("hora_cierre__isnull", False),
                        ("hora_apertura__lt", models.F("hora_cierre")),
                    ),
                    _connector="OR",
                ),
                name="ck_horario_horas",
            ),
        ),
        migrations.AddConstraint(
            model_name="horario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vigente_hasta__isnull", True),
                    ("vigente_desde__isnull", True),
                    ("vigente_hasta__gte", models.F("vigente_desde")),
                    _connector="OR",
                ),
                name="ck_horario_vigencia",
            ),
        ),
        migrations.AddIndex(
            model_name="tarifa",
            index=models.Index(fields=["atractivo"], name="idx_tarifa_atractivo"),
        ),
        migrations.AddIndex(
            model_name="tarifa",
            index=models.Index(
                fields=["atractivo", "monto"], name="idx_tarifa_atractivo_monto"
            ),
        ),
        migrations.AddIndex(
            model_name="tarifa",
            index=models.Index(fields=["tipo_tarifa"], name="idx_tarifa_tipo"),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto__gte", 0)), name="ck_tarifa_monto"
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vigente_hasta__isnull", True),
                    ("vigente_desde__isnull", True),
                    ("vigente_hasta__gte", models.F("vigente_desde")),
                    _connector="OR",
                ),
                name="ck_tarifa_vigencia",
            ),
        ),
        migrations.AddIndex(
            model_name="usuariorol",
            index=models.Index(fields=["rol"], name="idx_usuario_rol_rol"),
        ),
        migrations.AddConstraint(
            model_name="usuariorol",
            constraint=models.UniqueConstraint(
                fields=("usuario", "rol"), name="pk_usuario_rol"
            ),
        ),
    ]
