# Generated by Django 5.2.17 on 2026-09-15 13:36

import uuid
from decimal import Decimal

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaRecomendacion',
            fields=[
                ('id_consulta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presupuesto_bob', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('punto_partida', django.contrib.gis.db.models.fields.PointField(spatial_index=False, srid=4326)),
                ('macrodistrito', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'consulta_recomendacion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPreferencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivel_interes', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usuario_preferencia',
            },
        ),
        migrations.RenameIndex(
            model_name='atractivocategoria',
            new_name='idx_atractivo_cat_cat',
            old_name='idx_atractivo_categoria',
        ),
        migrations.RenameIndex(
            model_name='fuentedocumental',
            new_name='idx_fuente_doc_atractivo',
            old_name='idx_fuente_atractivo',
        ),
        migrations.AddField(
            model_name='atractivo',
            name='fuente_origen',
            field=models.CharField(default='INSTITUCIONAL', max_length=100),
        ),
        migrations.AddField(
            model_name='consultarecomendacion',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_recomendacion', to='turismo.usuario'),
        ),
        migrations.AddField(
            model_name='usuariopreferencia',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='turismo.categoria'),
        ),
        migrations.AddField(
            model_name='usuariopreferencia',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='turismo.usuario'),
        ),
        migrations.AddIndex(
            model_name='consultarecomendacion',
            index=models.Index(fields=['usuario'], name='idx_consulta_usuario'),
        ),
        migrations.AddIndex(
            model_name='consultarecomendacion',
            index=django.contrib.postgres.indexes.GistIndex(fields=['punto_partida'], name='idx_consulta_punto_partida_gist'),
        ),
        migrations.AddConstraint(
            model_name='consultarecomendacion',
            constraint=models.CheckConstraint(condition=models.Q(('presupuesto_bob__gte', Decimal('0.00'))), name='ck_consulta_presupuesto'),
        ),
        migrations.AddConstraint(
            model_name='consultarecomendacion',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_horas__gt', Decimal('0.00'))), name='ck_consulta_tiempo'),
        ),
        migrations.AddIndex(
            model_name='usuariopreferencia',
            index=models.Index(fields=['categoria'], name='idx_upref_categoria'),
        ),
        migrations.AddConstraint(
            model_name='usuariopreferencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'categoria'), name='pk_usuario_preferencia'),
        ),
        migrations.AddConstraint(
            model_name='usuariopreferencia',
            constraint=models.CheckConstraint(condition=models.Q(('nivel_interes__gte', Decimal('0.00')), ('nivel_interes__lte', Decimal('1.00'))), name='ck_usuario_preferencia_nivel'),
        ),
    ]
