# Generated by Django 5.2.17 on 2026-09-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turismo", "0002_consultarecomendacion_usuariopreferencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atractivo",
            name="fuente_origen",
            field=models.CharField(
                db_default="INSTITUCIONAL", default="INSTITUCIONAL", max_length=100
            ),
        ),
    ]
