# Generated by Django 5.2.17 on 2026-10-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turismo", "0004_mover_modelos_a_apps"),
    ]

    operations = [
        migrations.CreateModel(
            name="Foto",
            fields=[
                ("id_foto", models.BigAutoField(primary_key=True, serialize=False)),
                ("public_id", models.CharField(max_length=300, unique=True)),
                ("url", models.URLField(max_length=500)),
                ("ancho", models.IntegerField(blank=True, null=True)),
                ("alto", models.IntegerField(blank=True, null=True)),
                ("orden", models.IntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "atractivo",
                    models.ForeignKey(
                        db_column="id_atractivo",
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="turismo.atractivo",
                    ),
                ),
            ],
            options={
                "db_table": "foto",
                "indexes": [
                    models.Index(
                        fields=["atractivo", "orden"], name="idx_foto_atractivo_orden"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("orden__gte", 0)), name="ck_foto_orden"
                    )
                ],
            },
        ),
    ]
