# Generated by Django 5.2.17 on 2026-10-07 16:28

from django.db import migrations, models
from django.utils.text import slugify


def poblar_slugs(apps, schema_editor):
    Atractivo = apps.get_model("turismo", "Atractivo")
    for atractivo in Atractivo.objects.filter(slug=""):
        atractivo.slug = slugify(atractivo.nombre)[:120]
        atractivo.save(update_fields=["slug"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("turismo", "0005_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="atractivo",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="foto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("processing", "Procesando"),
                    ("completed", "Completada"),
                    ("failed", "Fallida"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="foto",
            name="tipo",
            field=models.CharField(
                choices=[("imagen", "Imagen"), ("video", "Video")],
                default="imagen",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="foto",
            name="url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.RunPython(poblar_slugs, noop),
    ]
